# Generated by Django 5.1.5 on 2025-01-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BibleVerse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("book", models.CharField(max_length=100)),
                ("chapter", models.IntegerField()),
                ("verse", models.IntegerField()),
                ("text", models.TextField()),
            ],
            options={
                "unique_together": {("book", "chapter", "verse")},
            },
        ),
    ]
